---
common_packages:
  - apt-show-versions
  - apt-transport-https
  - bash
  - ca-certificates
  - curl
  - cifs-utils
  - ecryptfs-utils
  - software-properties-common
  - htop
  - imagemagick
  - libc-client2007e
  - libc-client2007e-dev
  - libpam-mount
  - libindicator7
  - libreadline-dev
  - network-manager-openvpn-gnome
  - network-manager-openvpn
  - net-tools
  - tree
  - unattended-upgrades
  - unzip
  - vim
  - wget
  - zip
